name: download_assets
description: Download and uncompress assets
version: 3.0.0
homepage: https://github.com/edjostenes/download_assets

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  archive: ^3.1.6
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
